[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/install"
  to = "/.netlify/functions/install"
  status = 200

[[redirects]]
  from = "/install"
  to = "/install.html"
  status = 200

[[redirects]]
  from = "/api/paddle-webhook"
  to = "/.netlify/functions/paddle-webhook"
  status = 200
